### ISSUE TITLE
Pop Up vs Embed

### ISSUE THREAD

**Issue by Westy6711** [zl743/klaviyo-back-in-stock#1]
Hi there, this isn't an issue, I am new to GitHub so sorry if this is in the wrong place. The code looks like it's going to be spot on for what I need. But in an ideal world I would have this as an Embed rather than a pop up. I have tried to make these changes with little success. I am wondering if you have an tips so I can achieve this? Many thanks

**Comment by zl743** [comment]
Hi there,

If you need an embed I would suggest not including the CSS styles at all, as that is what styles the section as a popup. From there you can remove various elements in the section file that would no longer be needed such as the close button, and then work backwards to make your CSS styling fit in an embed scenario. good luck!
